[package]
name = "cloud-log-analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
main_error = "0.1.2"
thiserror = "1.0.63"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
regex = "1.10.5"
log = "0.4.22"
clap = { version = "=4.1.3", features = ["derive"] }
cloud-log-analyser-data = { version = "0.1.0", path = "./data" }
zip = "2.1.5"
itertools = "0.13.0"

[profile.dev.package."*"]
opt-level = 3